# In this notebook we will cover foundamental TensorFlow.

More specificaly, we're going cover to cover:
* Introguction tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* Use @tf.function (a way to speed up your regular Python functions)
* Using GPU with TensorFlow (or TPUs)
* Exercise to try for yourself !

## Introduction to Tensors

In [67]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [2]:
# Create tensord with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimension of a tensor (ndim)
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [5]:
vector.ndim

1

In [6]:
# Create a Matrix
matrix = tf.constant([[10, 7],
            [7, 10]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [7]:
matrix.ndim

2

In [8]:
# Create another matrix
another_matrix = tf.constant([[10, 7], [7, 10], [1, 3]], dtype=tf.float32) # Specify data type

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 1.,  3.]], dtype=float32)>

In [9]:
# What is number of domention is?
another_matrix.ndim

2

In [10]:
# Let's create a tensor
tensor = tf.constant([    [        [ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]
    ],
    [        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ],
    [        [19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]
    ]
]
)

tensor

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])>

In [11]:
tensor.ndim

3

What we've created so far:

* Scalor: A single number
* Vector: A number with direction (e.g. wind speed)
* Matrix: A 2-dimentional array of numbers
* Tensor: An n-dimentional array of numbers (when n can be any number)

### Creatinf tensors with `tf.Variable`

In [12]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [13]:
# Let's try change one of the element ussing assign
changeable_tensor[0].assign(7)

changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

## Creating random Tensors

Random tensors are tensors of some abitrary size wihich contain random numbers.

In [14]:
# Create two random tensors

random_1 = tf.random.Generator.from_seed(42) # Set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))


# Are they equal?

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of element in a tensor

In [15]:
# Shuffle a tensor (valuable for suffle the data so the inherent order did not effect learning)

not_shuffled = tf.constant([[10, 7], [3, 4], [2, 5]])

not_shuffled.ndim, not_shuffled

(2,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4],
        [ 2,  5]])>)

In [16]:
# Now shuffle the not_shuffle tensor

shuffled = tf.random.shuffle(not_shuffled)

shuffled.ndim, shuffled

(2,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 2,  5],
        [10,  7],
        [ 3,  4]])>)

In [17]:
tf.random.set_seed(42) # Global level seed
tf.random.shuffle(not_shuffled, seed=(42)) # Operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

> ☝ It looks like if wewant our shuffled tensors to be in the same order, we've got to use global level random seed as well as the operation level random seed.

### Others ways to make tensors:

In [18]:
#Create tensor with all ones

tf.ones([3, 2])

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [19]:
# Create tensor with all zeros

tf.zeros([3, 2])

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

## Turn Nimpy arrays into tensore.

The main difference between NumPy arrays and  TensorFlow tensors is that tensors can run on  a GPU (much faster for numerical computing).

In [20]:
# You can also turn numpy arrays into tensors

import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32) # Capital for matrix ot tensor, non-capital for vector.

numpy_A


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [21]:
A = tf.constant(numpy_A) # Turn it into tensor
B = tf.constant(numpy_A, shape=(2, 3, 4)) # We can also re-shape it

A, B

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>)

### Getting information from tensors

When dealing with tensors:
* Shape
* Rank
* Axis or Dimentsion
* Size

In [22]:
# Create a rank four tensors (4 dimensions)

rank4_tensor = tf.zeros([2, 3, 4, 5])

rank4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [23]:
rank4_tensor.shape, rank4_tensor.ndim, tf.size(rank4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [24]:
# Get various attributrs of our tensor

print("Datatype of every element:", rank4_tensor.dtype)
print("Number of dimensions (rank)", rank4_tensor.ndim)
print("Shape of tensor:", rank4_tensor.shape)
print("Elements along the 0 axies:", rank4_tensor.shape[0])
print("Element along last axix:", rank4_tensor.shape[-1])
print("Total number of the tensor:", tf.size(rank4_tensor).numpy())


Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank) 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axies: 2
Element along last axix: 5
Total number of the tensor: 120


### Indexing tensor
Tensors can be indexed just like Python list.

In [25]:
# Get the first 2 lwmwnts of each dimension

rank4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [26]:
# Get the first element from each dimension from each index expect for the final one

rank4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [27]:
# Create a rank 2 tansor (2 dimensions)

rank2_tensor = tf.constant([[10, 7], [3, 4]])

print("Number of dimensions (rank)", rank2_tensor.ndim)

Number of dimensions (rank) 2


In [28]:
# Get last item of each row

rank2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>

In [29]:
# Add in extra dimension to our rank 2 tensor

rank3_tensor = rank2_tensor[:, :, tf.newaxis] # Or [..., tf.newaxis]

rank3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [30]:
# Alternative way to do so

tf.expand_dims(rank2_tensor, axis=-1) # -1 means final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [31]:
rank2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

### Manipulating tensors (tensor operations)

**Basic operstions**

`+`, `-`, `*`, `/`


In [32]:
# You can add values to a tensor usind the addition operator

tensor = tf.constant([[10, 7], [3, 4]])

print(tensor + 10) # Original remain unchange

print((tensor - 10).numpy())

print((tensor * 10).numpy())

print((tensor / 10).numpy())

tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)
[[ 0 -3]
 [-7 -6]]
[[100  70]
 [ 30  40]]
[[1.  0.7]
 [0.3 0.4]]


In [33]:
# Wecan also use TensorFlow build in operator
# This way will do it faster than before ways

tf.multiply(tensor, 10).numpy()

tf.divide(tensor, 10).numpy()

array([[1. , 0.7],
       [0.3, 0.4]])

**Matrix Multiplication**

In machine learning, matrix multipication is one of the most common tensor operstors.

There are two rules our tensor (or matrix) need to fulfil if we're going to matrix mutiplication.:

1. The inner dimensions must match
2. The resulting matrix has the shape of the inner dimensions

In [34]:
# Matrix multiplication in TensorFlow

print(tensor)

print(tf.matmul(tensor, tensor).numpy())

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)
[[121  98]
 [ 42  37]]


In [35]:
# Matrix multiplication with Python operator "@"

print((tensor @ tensor).numpy())

[[121  98]
 [ 42  37]]


In [36]:
tensor.shape

TensorShape([2, 2])

In [37]:
# Create a tensor  (3, 2)

X = tf.constant([[1, 2], [3, 4], [5, 6]])

# Create another (3, 2)

Y = tf.constant([[3, 5], [7, 8], [9, 10]])

In [38]:
# Try to mutiply tensors of same shape
# X @ Y

In [39]:
#　We can change the shape of Y

Y = tf.reshape(Y, [2, 3])

print(Y.numpy())
print()
print(X.numpy())
print()

print("X @ Y = ")
print((X@Y).numpy())

[[ 3  5  7]
 [ 8  9 10]]

[[1 2]
 [3 4]
 [5 6]]

X @ Y = 
[[19 23 27]
 [41 51 61]
 [63 79 95]]


In [40]:
tf.matmul(X, Y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[19, 23, 27],
       [41, 51, 61],
       [63, 79, 95]])>

In [41]:
# Or what we can do is transpose


Y = tf.constant([[3, 5], [7, 8], [9, 10]])

print(Y)

tf.transpose(Y)

print(tf.transpose(Y))

tf.Tensor(
[[ 3  5]
 [ 7  8]
 [ 9 10]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 3  7  9]
 [ 5  8 10]], shape=(2, 3), dtype=int32)


**The dot product**

Matrix multiplication is also referref to as the dot product.

You can perform matrix mutiplication using:

*`tf.matmul`*

*`tf.tensordot`*

*`@`*

In [42]:
# Perform the dot product on X ad Y (requires X or Y to be transposed) 

"""
⚠️ Do not use reshappe ⚠️
"""

print(tf.tensordot(X, tf.transpose(Y), axes = 1).numpy(), "\n")

print(tf.matmul(X, tf.transpose(Y)).numpy())

[[ 13  23  29]
 [ 29  53  67]
 [ 45  83 105]] 

[[ 13  23  29]
 [ 29  53  67]
 [ 45  83 105]]


#### Generally, when performingmatrix matilipication on two tensors and one of the axes does not line up we will transpose rather then reshpae.

### Changing the data type of a tensor ?

In [43]:
# Create a new tensor with default flot32

B = tf.constant([1.7, 3.2])

B.dtype

tf.float32

In [44]:
C = tf.constant([1, 2])

C.dtype

tf.int32

In [45]:
# Change from float32 to float16 (resuce percision)

D = tf.cast(B, dtype=tf.float16)

D.dtype

tf.float16

In [46]:
# Change int32 to float32

E = tf.cast(C, dtype=tf.float32)

print("C was", C.dtype, ". Now it is ", E.dtype)

C was <dtype: 'int32'> . Now it is  <dtype: 'float32'>


### Aggregating tensors 🤐

Aggregation tensors = Condensing from mutiple values down to a samller amount of values.

In [47]:
# Getting abslute values

D = tf.constant([-7, -10])

tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

### Let's go through the following form of aggregation

* Get the min : *`tf.reduce_min`*

* Get the max: *`tf.reduce_max`*

* Get the mean: *`tf.reduce_mean`*

* Get the sum: *`tf.reduce_sum`*

In [48]:
# Create a random tensor with values between 0 ~ 100

E = tf.constant(np.random.randint(0, 100, size = 50))

E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([59, 99, 80, 17, 86, 22, 69, 72, 83, 53, 45, 66, 19, 31, 95, 67, 29,
       19, 20, 40, 22, 78, 62,  8, 42, 29, 26,  2, 22, 29, 17,  3, 80, 31,
       51, 82,  3,  0, 14,  4, 96, 59,  1, 13, 69, 70, 40, 16, 75, 84])>

In [49]:
print("Here is the minium:", tf.reduce_min(E).numpy())
print("Here is the maxium:", tf.reduce_max(E).numpy())
print("Here is the mean:", tf.reduce_mean(E).numpy())
print("Here is the sum:", tf.reduce_sum(E).numpy(), "\n")

"""
😯 Remember must cast type first 😯
"""

# Cast the dtype
E = tf.cast(E, dtype=tf.float32)

print("Here is a variance:", tf.math.reduce_variance(E).numpy())
print("Here is the standard deviation:", tf.math.reduce_std(E).numpy())


Here is the minium: 0
Here is the maxium: 99
Here is the mean: 43
Here is the sum: 2199 

Here is a variance: 891.1396
Here is the standard deviation: 29.851961


### Find the positional maximun and minimun  

In [50]:
# Create a new tensor for finding positional max and min

tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F.numpy()

array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)

In [51]:
# Find the positional Maximum

"""
😀tf.argmax(F) will give us the index😀
"""

print(F[tf.argmax(F)].numpy(), "\n")
print(tf.reduce_max(F).numpy())

assert F[tf.argmax(F)] == tf.reduce_max(F)

0.9671384 

0.9671384


In [52]:
# Find the positional minuium

print(F[tf.argmin(F)].numpy(), "\n")
print(tf.reduce_min(F).numpy())

0.009463668 

0.009463668


### Squeezing a tensor (removing all signal dimensions)

In [53]:
# Create a tensor to get started

tf.random.set_seed(42)

G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))

G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [54]:
# Squeezing 

print(G.shape)

G_squeeze = tf.squeeze(G)

print(G_squeeze.shape)

(1, 1, 1, 1, 50)
(50,)


### One-hot encoding tensors

In [55]:
# Create a list of indices
some_list = [0, 1, 2, 3] # Could be red, green, blue, purple

# One-hot encoding our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [56]:
# Specify custom values for one-hot encoding

tf.one_hot(some_list, depth=4, on_value = "I LUV learning", off_value="Also loke to dance")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'I LUV learning', b'Also loke to dance', b'Also loke to dance',
        b'Also loke to dance'],
       [b'Also loke to dance', b'I LUV learning', b'Also loke to dance',
        b'Also loke to dance'],
       [b'Also loke to dance', b'Also loke to dance', b'I LUV learning',
        b'Also loke to dance'],
       [b'Also loke to dance', b'Also loke to dance',
        b'Also loke to dance', b'I LUV learning']], dtype=object)>

### Squaring, log, squarw root

In [57]:
# Create a tensor
H = tf.range(1., 10.)

H

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [58]:
# Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([ 1.,  4.,  9., 16., 25., 36., 49., 64., 81.], dtype=float32)>

In [59]:
# Square root
"""
💫Require the dtype be float💫
"""

H_cast = tf.cast(H, dtype=tf.float32)
print(tf.math.sqrt(H_cast).numpy())

[1.        1.4142135 1.7320508 2.        2.236068  2.4494898 2.6457512
 2.828427  3.       ]


In [60]:
# Find the log
print(tf.math.log(H_cast).numpy())

[0.        0.6931472 1.0986123 1.3862944 1.609438  1.7917595 1.9459102
 2.0794415 2.1972246]


### Tensors and Numpy

TensorFlow interacts beautifully with Numpy arrays

In [62]:
# Create a tensor directly from a numpy array
J = tf.constant(np.array([1., 2, 3, 4, 5]))

J

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([1., 2., 3., 4., 5.])>

In [63]:
# Convert our tensor back to Numpy array
np.array(J), type(np.array(J))

(array([1., 2., 3., 4., 5.]), numpy.ndarray)

In [65]:
# Convert tensor J to a Numpy array
J.numpy(), type(J.numpy())

##print(J.numpy()[2])

3.0


In [66]:
# Default types of each slightly different
numpy_J = tf.constant(np.array([3., 7., 4.]))
tensor_J = tf.constant([3., 7., 4.])

# Check the datatype of each 👀
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)